In [1]:
import numpy as np


In [3]:
student=np.array([68,70,80,90,100,101])

In [4]:
student

array([68, 70, 80, 90])

In [5]:
print(student[1])

70


In [6]:
print("from point to point",student[1:5])


from point to point [70 80 90]


In [7]:
print(student[1])

70


In [8]:
print(student[1:4])

[70 80 90]


In [15]:
studentList=np.array(['anwer','nuur', 'axmad','abdi'])

In [16]:
print(studentList[2])

axmad


In [17]:
array1=np.array([68,90])

In [18]:
array1

array([68, 90])

In [21]:
array2=np.array([70,80])

In [22]:
array1+array2

array([138, 170])